### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

### ISSUE THREAD

**Issue by 28utkarsh** [allenai/qasper-led-baseline#24]
```
$ allennlp train training_config/led_base_with_evidence_scaffold.jsonnet -s output --include-package qasper_baselines

Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 5, in <module>
    from allennlp.__main__ import run
  File "/usr/local/lib/python3.8/dist-packages/allennlp/__init__.py", line 18, in <module>
    import transformers, spacy, torch, numpy  # noqa
  File "/usr/local/lib/python3.8/dist-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.8/dist-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/versions.py", line 85, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'
```

**Comment by 28utkarsh** [comment]
Downgrading the packaging module works for me.
`pip install packaging==21.3`
