### ISSUE TITLE
evaluate model using gold evidence

### ISSUE THREAD

**Issue by HenryPaik1** [allenai/qasper-led-baseline#9]
Hi I am struggling with evaluating model by only using gold evidence to re-implement table 4 in the paper.
I ran the command line below after fine-tuning model and changed config file after saving model (model.tar.gz):
```
allennlp evaluate source/model_reconf.tar.gz data/qasper-dev-v0.1.json --output-file "log/result.txt" --cuda-device 0 --include-package qasper_baselines
```
and it is the revised config file in model.tar.gz: 
```
{
    "dataset_reader": {
        "type": "qasper",
        "for_training": true,
        "max_document_length": 15360,
        "transformer_model_name": "allenai/led-base-16384"
    },
    "model": {
        "type": "qasper_baseline",
        "attention_dropout": 0.1,
        "attention_window_size": 1536,
        "gradient_checkpointing": true,
        "transformer_model_name": "allenai/led-base-16384",
        "use_evidence_scaffold": true
    },
    "train_data_path": "data/qasper-train-dev-v0.1/qasper-train-v0.1.json",
    "validation_data_path": "data/qasper-train-dev-v0.1/qasper-dev-v0.1.json",
    "trainer": {
        "callbacks": [
            {
                "type": "tensorboard"
            }
        ],
        "cuda_device": 0,
        "enable_default_callbacks": false,
        "grad_clipping": 1,
        "learning_rate_scheduler": {
            "type": "slanted_triangular",
            "cut_frac": 0.1,
            "num_epochs": 15,
            "num_steps_per_epoch": 1336
        },
        "num_epochs": 15,
        "num_gradient_accumulation_steps": 2,
        "optimizer": {
            "type": "adam",
            "lr": 5e-05
        },
        "patience": 15,
        "use_amp": true,
        "validation_metric": "+answer_f1"
    },
    "vocabulary": {
        "type": "empty"
    },
    "data_loader": {
        "batch_size": 1
    },
    "pytorch_seed": 15371,
    "validation_dataset_reader": {
        "type": "qasper",
        "context": "question_and_evidence",
        "for_training": false,
        "max_document_length": 15360,
        "transformer_model_name": "allenai/led-base-16384"
    }
}
```

But I got an error msg as follows:
```
root@user:/workspace/# allennlp evaluate source/model_reconf2.tar.gz data/qasper-dev-v0.1.json --output-file "log/result.txt" --cuda-device 0 --include-package qasper_baselines
2021-06-18 03:22:44,643 - INFO - allennlp.common.plugins - Plugin allennlp_models available
2021-06-18 03:22:44,689 - INFO - allennlp.models.archival - loading archive file source/model_reconf2.tar.gz
2021-06-18 03:22:44,689 - INFO - allennlp.models.archival - extracting archive file source/model_reconf2.tar.gz to temp dir /tmp/tmpiasc50r5
2021-06-18 03:22:59,860 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmpiasc50r5/vocabulary.
2021-06-18 03:23:18,394 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpiasc50r5
2021-06-18 03:23:18,481 - INFO - allennlp.common.checks - Pytorch version: 1.7.1
2021-06-18 03:23:18,482 - INFO - allennlp.commands.evaluate - Reading evaluation data from data/qasper-dev-v0.1.json
loading instances: 0it [00:00, ?it/s]2021-06-18 03:23:18,483 - INFO - qasper_baselines.dataset_reader - Reading the dataset
2021-06-18 03:23:18,483 - INFO - qasper_baselines.dataset_reader - Reading json file at data/qasper-dev-v0.1.json
loading instances: 755it [00:01, 497.13it/s]2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - Stats:
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - number of documents: 281
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - number of questions: 1005
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - number of answers: 1764
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - questions with multiple answers: 744
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - extractive questions: 962
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - extractive questions with multiple spans: 406
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - multiple_evidence_spans_count: 536
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - answers with table or figure as evidence: 212
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - freeform answers: 431
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - yes/no questions: 208
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - answers with no evidence: 212
2021-06-18 03:23:20,448 - INFO - qasper_baselines.dataset_reader - unanswerable questions: 163
loading instances: 794it [00:01, 403.31it/s]
2021-06-18 03:23:20,564 - INFO - allennlp.training.util - Iterating over dataset
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.8/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/opt/conda/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/opt/conda/lib/python3.8/site-packages/allennlp/commands/evaluate.py", line 158, in evaluate_from_args
    metrics = evaluate(
  File "/opt/conda/lib/python3.8/site-packages/allennlp/training/util.py", line 359, in evaluate
    output_dict = model(**batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/MRC/qasper_baselines/model.py", line 129, in forward
    evidence_loss = loss_fn(evidence_logits.view(-1, 2), evidence.view(-1))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 961, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2261, in nll_loss
    raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
ValueError: Expected input batch_size (1) to match target batch_size (63).
```

Would you give me an advice? Thanks.

**Comment by pdasigi** [comment]
@HenryPaik1 Sorry for the delay in responding to your issue. I was not watching this repository earlier, so I never got notified of this issue. I am now, so I can give timely responses to future issues.

It looks like the error is with computing the evidence loss, which should not be computed in an answer-given-evidence model,  at all. You will need to set `use_evidence_scaffold` to `false` in your `model` config. Also, it looks like you set `context` to `question_and_evidence` in your `validation_dataset_reader`, but not in your `dataset_reader` config. Note that the `dataset_reader` config is used on your training data. So this means your model is still getting trained to predict answers given the entire paper text, and getting validated in the oracle evidence setting. You will need to modify the `dataset_reader`'s `context` setting as well. Hope this helps.
